"""Helper CLI used by humans and by the planner / generator / healer agents.

    python -m framework.cli validate [files...]   static-check CSV tests (no browser)
    python -m framework.cli keywords [--markdown] list keywords (the agents' vocabulary)
    python -m framework.cli locators              list object-repository elements
"""
from __future__ import annotations

import argparse
import itertools
import sys
from pathlib import Path

from .config import ROOT, load_settings
from .keywords import all_keywords
from .object_repository import ObjectRepository
from .validator import validate_files


def discover_csv(settings, include_seed: bool = False) -> list[Path]:
    files = []
    for path in sorted(settings.test_cases_dir.rglob("*.csv")):
        rel = path.relative_to(settings.test_cases_dir)
        if path.name.startswith("_"):
            continue
        if "seed" in rel.parts and not include_seed:
            continue
        files.append(path)
    return files


def render_keywords_markdown() -> str:
    out = [
        "# Keyword reference",
        "",
        "> Generated by `python -m framework.cli keywords --markdown > specs/keywords.md`. Do not edit by hand.",
        "",
        "## CSV format",
        "",
        "```",
        "test_id,test_name,tags,keyword,target,value,description",
        "```",
        "",
        "- One row = one step. Steps of a test are consecutive rows sharing a `test_id` (blank `test_id` continues the previous test).",
        "- `test_name` and `tags` (separated by `;`) are read from the first row of a test.",
        "- Cells containing a comma must be wrapped in double quotes; double any quote inside.",
        "- A row whose first cell starts with `#` is a comment.",
        "- **target** = which element (see locator forms below). **value** = text/URL/number/expected result.",
        "- Variables: `${NAME}`, `${env.NAME}`, `${env.NAME:-default}`, `${config.base_url}`, `${timestamp}`, `${uuid}`, `${random}`, `${date}`.",
        "- Tags: `smoke`, `regression`, `external` ... become pytest markers. `skip` / `fixme` disable the test.",
        "",
        "## Locator forms (target column)",
        "",
        "| Form | Example |",
        "|---|---|",
        "| Object repository | `@google.search_box` |",
        "| Role | `role=button[name=\"Search\"]` (quotes optional; `,exact=true` allowed) |",
        "| Label / placeholder | `label=Username`, `placeholder=Search` |",
        "| Text / alt / title | `text=Sign in`, `alt=Logo`, `title=Help` |",
        "| Test id | `testid=submit` |",
        "| CSS / XPath | `css=#search a h3`, `xpath=//h1`, or plain `#search` |",
        "| Pick one match | append ` >> first`, ` >> last` or ` >> nth=2` |",
        "",
        "Preference order: role > label > placeholder > text > testid > css/xpath. Put every locator in "
        "`object_repository/*.csv` and reference it as `@name`.",
        "",
    ]
    for category, group in itertools.groupby(all_keywords(), key=lambda k: k.category):
        out += [f"## {category}", "",
                "| Keyword | Aliases | target | value | What it does | Example (keyword,target,value) |",
                "|---|---|---|---|---|---|"]
        for spec in group:
            aliases = ", ".join(f"`{a}`" for a in spec.aliases) or "-"
            ex_t, ex_v = spec.example
            example = f"`{spec.name},{_csv_cell(ex_t)},{_csv_cell(ex_v)}`"
            out.append(f"| `{spec.name}` | {aliases} | {spec.target} | {spec.value} | "
                       f"{spec.doc.replace('|', '/')} | {example} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _csv_cell(text: str) -> str:
    return f'"{text.replace(chr(34), chr(34) * 2)}"' if "," in text or '"' in text else text


def cmd_validate(args) -> int:
    settings = load_settings()
    repo = ObjectRepository.load(settings.object_repo_dir)
    paths = [Path(p) for p in args.files] or discover_csv(settings)
    if not paths:
        print("No CSV test files found.")
        return 1
    scenarios, issues = validate_files(paths, repo)
    for issue in issues:
        print(issue)
    errors = sum(i.level == "error" for i in issues)
    print(f"\n{len(paths)} file(s), {len(scenarios)} test(s), {errors} error(s), {len(issues) - errors} warning(s)")
    return 1 if errors else 0


def cmd_keywords(args) -> int:
    if args.markdown:
        sys.stdout.write(render_keywords_markdown())
        return 0
    for spec in all_keywords():
        alias = f"  (aliases: {', '.join(spec.aliases)})" if spec.aliases else ""
        print(f"{spec.category:15} {spec.name:32} target={spec.target:9} value={spec.value:9}{alias}")
    return 0


def cmd_locators(_args) -> int:
    repo = ObjectRepository.load(load_settings().object_repo_dir)
    for name in repo.names():
        print(f"@{name:40} {repo.get(name)}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m framework.cli", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    v = sub.add_parser("validate", help="static-check CSV tests")
    v.add_argument("files", nargs="*", help="CSV files (default: everything under test_cases/, except seed/)")
    v.set_defaults(func=cmd_validate)
    k = sub.add_parser("keywords", help="list keywords")
    k.add_argument("--markdown", action="store_true", help="emit the markdown reference")
    k.set_defaults(func=cmd_keywords)
    sub.add_parser("locators", help="list object repository").set_defaults(func=cmd_locators)
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
